.PHONY: clean All

All:
	@echo "----------Building project:[ 21_PrintFileContentInReverse - Debug ]----------"
	@cd "21_PrintFileContentInReverse" && "$(MAKE)" -f  "21_PrintFileContentInReverse.mk"
clean:
	@echo "----------Cleaning project:[ 21_PrintFileContentInReverse - Debug ]----------"
	@cd "21_PrintFileContentInReverse" && "$(MAKE)" -f  "21_PrintFileContentInReverse.mk" clean
